### PR TITLE
Environment file

### PR DESCRIPTION
**Pull request by reppard**

### CODE REVIEW

**Comment by ajsmith** [comment]
Thank you for your contribution and my apologies for the delayed response!

I have to say I'm not entirely sold on the use of systemd environment files. This change has the benefit of simplifying some of the test output, but it also introduces some complexity. Also, systemd environment files typically provide a way for the user to further customize a unit beyond the default options, but in this case it seems to move existing configuration to another file without adding the ability to customize. This makes me think that this feature is not yet necessary, although I encourage you to prove me wrong especially if you have some specific use cases in mind.

**Comment by reppard** [comment]
No worries at all and thank you for your reply.  Looking at this PR now, I should have probably added a little more detail about my use case here.  At my org we have been using puppet masterlessly to provision AMIs which has been awesome but sometimes we need a way to upgrade the images referenced in these generated systemd units.  Adding the environment file gives me the flexibility of having a default image:tag/command and a means of modifying that service without some crazy sed awk stuff in user-data. 

For example I could have user-data/butt-init overwrite the environment file to start the service with a new image.  This works but has the limitation of only being able to update the image when booting a fresh instance.

Our current and preferred method is to have Consul Template watch and generate that environment file  post boot.  Then we simply need to update the value of image in Consul and our new image gets pulled and the service is bounced.  I hope I communicated our use case properly.  Thanks for the great module!

**Comment by ajsmith** [comment]
Okay, I can see how that would be useful! I think I'd like to implement this slightly differently, to provide general support for systemd environment files and allow for setting any options you might want in the environment file. I'd also like to make the use of an environment file completely optional. I'll add this feature to the next release, and once I've added it to the release branch I'll ask you to take a look to make sure it still does what you need it to do :)

**Comment by ajsmith** [comment]
@reppard - I implemented this on the 0.3 branch. It's a slightly different implementation, but I think it will still satisfy your use case. For example usage see `tests/systemd_env_file.pp`. If you have any feedback or questions, just let me know.

**Pull request closed without merging**
